### PR TITLE
Adding the error estimation to the trilateration

### PR DESCRIPTION
**Pull request by Samuel38**
I have added the error estimation, as well as some improvements to the position estimation. 

To improve accuracy, only Range combinations that have an error less than twice the median value are kept, as some can have very large errors and compromise the whole set.
During my tests on series of 10000 measurements with random data, in average, we reject about 1/3 of the combinations.

The error estimate is adjusted so that <Actual error/Estimated error> = 1.
However, the distributions of errors do not match between the actual and estimate. 
This leads to the Actual error being more likely to be bellow the estimated one.
When the Actual error overshoots the Estimated one, the error can however sometimes reach a factor of 10.
But generally, High value of Estimated error => High value of Actual error. They are pretty well correlated. 

The distributions of horizontal and vertical errors, as well as the distribution of the ratio actual/estimated error are displayed in the attached files (For this batch, I take 10000 series of 5 measurements from a distance between 40km and 55km located in a cone of angle +/-5° above the target which is on the ground of mars. With these conditions, The horizontal error is most likely going to be around 5m with an estimation around 10m, but due to the wide tail of the distribution, the average error will be 160m). 
Horizontal error distribution
Vertical error distribution
Actual vs Estimated error ratio distribution

### CODE REVIEW

**Comment by Samuel38** [comment]
One small note is that if there is a large number of Range measurements, the number of combinations increases rapidly, as it's !N/(!4*!(N-4)), so it increases as N^4. It can make the calculation become pretty slow when N > 10. 
Ideally, the script should be able to split the trilateration resolution over several updates if necessary. 
That might be something to look into in the future, especially if spotter ships fleets become a thing.

**Comment by Samuel38** [comment]
We should also probably consider only updating the trilateration if the text panel has changed.

**Comment by wakjah** [comment]
Looks very good.

The maths is far beyond what I comprehend but I'm sure you've got it covered!

I have added your performance comments as issues.

**Comment by Samuel38** [comment]
The math actually isn't too bad. 
It turns out the expression of x, y and z is a second order polynomial in the different distances. 
So I simply expressed dx, dy and dz with the second order limited development of these quantities. And as luck would have it, we can simplify all that by using only a few determinants, so everything factors well. 
So I inject the typical error of the distances as 5m and get an error vector that I can project on horizontal and vertical directions. 

Once that done, I just ran the script many times for different number of Range measurements and compared the average estimated and actual error as a function of the number of combination, and figured out how it should normalize. 
I don't really get why it came out with those values, but distributions are a mess, so beats me. All that matters is that it works in average.

**Pull request merged**
